// Generates app/api/divisionSales.ts from the reference Excel
// `สินค้าตาม divisionsale.xlsx` (sheet "Sheet1"), which maps สหพัฒน์ product
// lines to a division-sale letter (A / N / P / H).
//
// Sheet1 columns: [กลุ่มสินค้า, สินค้า, divisionsale]. Row 0 is the header.
// Product name (col 1) has leading spaces — trimmed. Division letter is col 2.
//
// Re-run after editing the Excel:  node scripts/gen_division_sales.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import XLSX from 'xlsx'

const __dirname = dirname(fileURLToPath(import.meta.url))
const XLSX_PATH = join(__dirname, '..', '..', 'สินค้าตาม divisionsale.xlsx')
const OUT_PATH = join(__dirname, '..', 'api', 'divisionSales.ts')

const wb = XLSX.read(readFileSync(XLSX_PATH))
const ws = wb.Sheets['Sheet1']
if (!ws) throw new Error('Sheet1 not found in ' + XLSX_PATH)

const raw = XLSX.utils.sheet_to_json(ws, { header: 1, defval: '' })
const entries = []
for (let i = 1; i < raw.length; i++) {
  const row = raw[i]
  const name = String(row[1] ?? '').trim()
  const div = String(row[2] ?? '').trim()
  if (!name || !div) continue
  entries.push({ name, div })
}

// Verify counts the user supplied.
const counts = entries.reduce((acc, e) => ((acc[e.div] = (acc[e.div] || 0) + 1), acc), {})
console.log('total entries:', entries.length)
console.log('per-division counts:', JSON.stringify(counts))

const entriesLiteral = entries
  .map((e) => `  { name: ${JSON.stringify(e.name)}, div: ${JSON.stringify(e.div)} },`)
  .join('\n')

const out = `// AUTO-GENERATED by scripts/gen_division_sales.mjs from "สินค้าตาม divisionsale.xlsx".
// Do not edit by hand — update the Excel and re-run: node scripts/gen_division_sales.mjs
//
// Maps สหพัฒน์ product lines to a division-sale letter (A / N / P / H).

export const DIVISION_SALES: { name: string; div: string }[] = [
${entriesLiteral}
]

/** Mapping formatted compactly, grouped by division, for the extraction prompt. */
export function divisionSalesPromptBlock(): string {
  const byDiv = new Map<string, string[]>()
  for (const { name, div } of DIVISION_SALES) {
    if (!byDiv.has(div)) byDiv.set(div, [])
    byDiv.get(div)!.push(name)
  }
  return [...byDiv.entries()]
    .map(([div, names]) => \`Division \${div}: \${names.join(', ')}\`)
    .join('\\n')
}
`

writeFileSync(OUT_PATH, out)
console.log('wrote', OUT_PATH)
